version: '3'
services:
  api:
    build: .
    ports:
     - "${API_PORT}:${API_PORT}"
    volumes:
     - .:/opt/exchange/
    depends_on:
      - "mongodb"
  mongodb:
    image: "mvertes/alpine-mongo:latest"
    ports:
     - "27017:27017"
    volumes:
     - ./db_volume:/data/db